DataError
sqlalchemy.exc.DataError: (psycopg.errors.StringDataRightTruncation) значение не умещается в тип character varying(255)
[SQL: UPDATE users SET avatar=%(avatar)s::VARCHAR WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'avatar': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAYAAAB/HSuDAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAtGVYSWZJSSoACAAAAAYAEgEDAAEAAAABAAAAGgEFAAEAAABWAAA ... (85296 characters truncated) ... lmPRqQ0enWjG1a0wGvUoxNjkYDB2ypLSqDZ0tGsXYYlJMLQ6dHXUmjbpOUWtq1Iq+vNPkXHJ6WlJhyjceHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyY78f8EQTZ7KC79PAAAAAElFTkSuQmCC', 'users_id': 4}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)

Traceback (most recent call last)
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
self.dialect.do_execute(
^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
cursor.execute(statement, parameters)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\psycopg\cursor.py", line 97, in execute
raise ex.with_traceback(None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The above exception was the direct cause of the following exception:
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\flask\app.py", line 2213, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\app\routes\account.py", line 41, in profile
db.session.commit()
^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
return self._proxied.commit()
       ^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2028, in commit
trans.commit(_to_root=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<string>", line 2, in commit
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
ret_value = fn(self, *arg, **kw)
            ^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
self._prepare_impl()
^^^^^^^^^^^^^^^^^^^^
File "<string>", line 2, in _prepare_impl
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
ret_value = fn(self, *arg, **kw)
            ^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
self.session.flush()
^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4352, in flush
self._flush(objects)
^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4487, in _flush
with util.safe_reraise():
     ^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
raise exc_value.with_traceback(exc_tb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4448, in _flush
flush_context.execute()
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
rec.execute(self)
^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
util.preloaded.orm_persistence.save_obj(
^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
_emit_update_statements(
^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 912, in _emit_update_statements
c = connection.execute(
    
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
return meth(
       
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
return connection._execute_clauseelement(
       
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
ret = self._execute_context(
      
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
return self._exec_single_context(
       
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
self._handle_dbapi_exception(
^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
self.dialect.do_execute(
^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
cursor.execute(statement, parameters)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Projects\Room2room-Tour\.venv\Lib\site-packages\psycopg\cursor.py", line 97, in execute
raise ex.with_traceback(None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.DataError: (psycopg.errors.StringDataRightTruncation) значение не умещается в тип character varying(255)
[SQL: UPDATE users SET avatar=%(avatar)s::VARCHAR WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'avatar': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAYAAAB/HSuDAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAtGVYSWZJSSoACAAAAAYAEgEDAAEAAAABAAAAGgEFAAEAAABWAAA ... (85296 characters truncated) ... lmPRqQ0enWjG1a0wGvUoxNjkYDB2ypLSqDZ0tGsXYYlJMLQ6dHXUmjbpOUWtq1Iq+vNPkXHJ6WlJhyjceHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyY78f8EQTZ7KC79PAAAAAElFTkSuQmCC', 'users_id': 4}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object